version: '3.8'

services:
  mysql:
    image: mariadb:10.5
    container_name: mysql
    env_file: .env.mysql
    restart: unless-stopped
    volumes:
      - ./pdns-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      dnsnet:
        ipv4_address: 172.28.0.2

  pdns-auth:
    image: pschiffe/pdns-mysql
    container_name: pdns-auth
    env_file: .env.auth
    restart: unless-stopped
    depends_on:
      - mysql
#    ports:
#      - "5300:53/udp"
#      - "5300:53/tcp"
    networks:
      dnsnet:
        ipv4_address: 172.28.0.3

  pdns-recursor:
    image: pschiffe/pdns-recursor
    container_name: pdns-recursor
    restart: unless-stopped
#    ports:
#      - "5301:53/udp"
#      - "5301:53/tcp"
    networks:
      dnsnet:
        ipv4_address: 172.28.0.4
    volumes:
      - ./recursor.conf:/etc/pdns-recursor/recursor.conf

  dnsdist:
    build:
      context: ./dnsdist
    container_name: dnsdist
    restart: unless-stopped
    volumes:
      - ./dnsdist/dnsdist.conf:/etc/dnsdist/dnsdist.conf
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    depends_on:
      - mysql
      - pdns-auth
      - pdns-recursor
    networks:
      dnsnet:
        ipv4_address: 172.28.0.5

  pdns-admin-mysql:
    image: pschiffe/pdns-admin
    container_name: pdns-admin
    env_file: .env.admin
    restart: unless-stopped
#    ports:
#      - '127.0.0.1:8080:8080'
    networks:
      dnsnet:
        ipv4_address: 172.28.0.6
    depends_on:
      - mysql
      - pdns-auth
    volumes:
      - ./pdns-admin-data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/html
      - ./nginx/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - pdns-admin-mysql
    restart: unless-stopped
    networks:
      dnsnet:
        ipv4_address: 172.28.0.7

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/html
      - ./nginx/letsencrypt:/var/lib/letsencrypt
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/html; sleep 12h & wait $${!}; done'
    restart: unless-stopped
    networks:
      dnsnet:
        ipv4_address: 172.28.0.8

networks:
  dnsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
